// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task2AsepPlanning.Data;

#nullable disable

namespace Task2AsepPlanning.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250728072025_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Task2AsepPlanning.Models.Planning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Jumat")
                        .HasColumnType("int");

                    b.Property<int>("JumatResult")
                        .HasColumnType("int");

                    b.Property<int>("Kamis")
                        .HasColumnType("int");

                    b.Property<int>("KamisResult")
                        .HasColumnType("int");

                    b.Property<int>("Minggu")
                        .HasColumnType("int");

                    b.Property<int>("MingguResult")
                        .HasColumnType("int");

                    b.Property<int>("Rabu")
                        .HasColumnType("int");

                    b.Property<int>("RabuResult")
                        .HasColumnType("int");

                    b.Property<int>("Sabtu")
                        .HasColumnType("int");

                    b.Property<int>("SabtuResult")
                        .HasColumnType("int");

                    b.Property<int>("Selasa")
                        .HasColumnType("int");

                    b.Property<int>("SelasaResult")
                        .HasColumnType("int");

                    b.Property<int>("Senin")
                        .HasColumnType("int");

                    b.Property<int>("SeninResult")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Plannings");
                });
#pragma warning restore 612, 618
        }
    }
}
